### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by rubensworks** [comunica/Article-ISWC2019-AMF#5]
@RubenVerborgh Could you have a look at this?

The things we already had in here remain largely unchanged.
I mainly added some things based on comments from the last reviews.

Due to the new template, we have a lot more space, so I re-added a bunch of things we had to remove for last submission, and added some clarifications and examples where it made sense.

We still have 3/4 page left, so if you have any suggestions on things to add, please let me know.

**Comment by RubenVerborgh** [comment]
In https://github.com/comunica/Article-CIKM2020-AMF/tree/reviews/rv

Really good stuff; very insightful conclusion in particular.

With regard to space: perhaps some more high-level context in the intro might help, to make the paper accessible to a wider audience. But no immediate content gaps.

**Comment by rubensworks** [comment]
Thanks! :)
